<?php
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Личный кабинет");
?><?$APPLICATION->IncludeComponent(
	"bitrix:sale.personal.section",
	"b2bportal",
	array(
		"ACCOUNT_PAYMENT_ELIMINATED_PAY_SYSTEMS" => array(
			0 => "0",
		),
		"ACCOUNT_PAYMENT_PERSON_TYPE" => "1",
		"ACCOUNT_PAYMENT_SELL_CURRENCY" => "RUB",
		"ACCOUNT_PAYMENT_SELL_SHOW_FIXED_VALUES" => "Y",
		"ACCOUNT_PAYMENT_SELL_TOTAL" => array(
			0 => "100",
			1 => "200",
			2 => "500",
			3 => "1000",
			4 => "5000",
			5 => "",
		),
		"ACCOUNT_PAYMENT_SELL_USER_INPUT" => "N",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ALLOW_INNER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "3600",
		"CACHE_TYPE" => "A",
		"CHECK_RIGHTS_PRIVATE" => "N",
		"COMPATIBLE_LOCATION_MODE_PROFILE" => "N",
		"CUSTOM_PAGES" => "[[\"#SITE_DIR#personal/docs/\",\"Документы\",\"flaticon2-file-1\"],[\"#SITE_DIR#personal/claims/\",\"Рекламации\",\"flaticon2-warning\"],[\"#SITE_DIR#personal/kompred/\",\"Коммерческие предложения\",\"flaticon2-paper\"],[\"#SITE_DIR#personal/balance/\",\"Баланс\",\"flaticon2-line-chart\"]]",
		"CUSTOM_SELECT_PROPS" => array(
		),
		"MAIN_CHAIN_NAME" => "",
		"NAV_TEMPLATE" => "",
		"ONLY_INNER_FULL" => "N",
		"ORDERS_PER_PAGE" => "20",
		"ORDER_DEFAULT_SORT" => "STATUS",
		"ORDER_HIDE_USER_INFO" => array(
			0 => "0",
		),
		"ORDER_HISTORIC_STATUSES" => array(
			0 => "F",
		),
		"ORDER_REFRESH_PRICES" => "N",
		"ORDER_RESTRICT_CHANGE_PAYSYSTEM" => array(
			0 => "0",
		),
		"PATH_TO_BASKET" => "#SITE_DIR#personal/cart/",
		"PATH_TO_CATALOG" => "#SITE_DIR#catalog/",
		"PATH_TO_CONTACT" => "#SITE_DIR#contacts/",
		"PATH_TO_PAYMENT" => "#SITE_DIR#personal/order/payment/",
		"PROFILES_PER_PAGE" => "20",
		"SAVE_IN_SESSION" => "N",
		"SEF_FOLDER" => "#SITE_DIR#personal/",
		"SEF_MODE" => "Y",
		"SEND_INFO_PRIVATE" => "N",
		"SET_TITLE" => "Y",
		"SHOW_ACCOUNT_COMPONENT" => "Y",
		"SHOW_ACCOUNT_PAGE" => "N",
		"SHOW_ACCOUNT_PAY_COMPONENT" => "Y",
		"SHOW_BASKET_PAGE" => "Y",
		"SHOW_CONTACT_PAGE" => "N",
		"SHOW_ORDER_PAGE" => "Y",
		"SHOW_PRIVATE_PAGE" => "Y",
		"SHOW_PROFILE_PAGE" => "Y",
		"SHOW_SUBSCRIBE_PAGE" => "N",
		"USE_AJAX_LOCATIONS_PROFILE" => "N",
		"COMPONENT_TEMPLATE" => "b2bportal",
		"PROP_#OFFERS_OFFERS_IBLOCK_ID#" => array(
		),
		"PROP_#CATALOG_CATALOG_IBLOCK_ID#" => array(
		),
		"ORDER_DISALLOW_CANCEL" => "N",
		"CLAIMS_PATH" => "#SITE_DIR#personal/claims/?UF_ORDER_ID=#ORDER_NUMBER#",
		"USE_CLAIMS" => "Y",
		"ADD_CLAIM_PATH" => "#SITE_DIR#personal/claims/?ID=0&edit=1&UF_ORDER_ID=#ORDER_NUMBER#",
		"SORT_FIELDS" => array(
		),
		"SORT_DEFAULT_FIELD" => "name",
		"SORT_DEFAULT_ORDER" => "asc",
		"PERPAGE_FIELDS" => array(
			0 => "10",
			1 => "25",
			2 => "50",
			3 => "",
		),
		"PERPAGE_DEFAULT" => "10",
		"URL_TO_ADD" => "#SITE_DIR#personal/company_add/",
		"CLAIM_DETAIL" => "#SITE_DIR#personal/claims/?ID=#ID#&edit=1",
		"COMPANIES_HEADERS" => array(
			0 => "PHONE",
			1 => "COMPANY",
			2 => "INN",
		),
		"COMPANIES_HEADERS_SORT" => array(
			0 => "PROPS_PHONE",
			1 => "PROPS_COMPANY",
			2 => "PROPS_INN",
		),
		"DOCUMENTS_IBLOCK_TYPE" => "system",
		"DOCUMENTS_IBLOCK_ID" => "#SYSTEM_DOCS_IBLOCK_ID#",
		"KOMPRED_PATH" => "#SITE_DIR#personal/kompred/",
		"SEF_URL_TEMPLATES" => array(
			"index" => "index.php",
			"orders" => "orders/",
			"account" => "account/",
			"subscribe" => "subscribe/",
			"profile" => "companies/",
			"profile_detail" => "companies/#ID#/",
			"private" => "profile/",
			"order_detail" => "orders/#ID#/",
			"order_cancel" => "cancel/#ID#/",
		)
	),
	false
);?><? require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php"); ?>